service: employee-crud-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 20
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  createEmployee:
    handler: src/handlers/employeeHandler.createEmployee
    events:
      - http:
          path: employees
          method: post
          cors: true  

  getEmployee:
    handler: src/handlers/employeeHandler.getEmployee
    events:
      - http:
          path: employees/{id}
          method: get
          cors: true  

  listEmployees:
    handler: src/handlers/employeeHandler.listEmployees
    events:
      - http:
          path: employees
          method: get
          cors: true  

  updateEmployee:
    handler: src/handlers/employeeHandler.updateEmployee
    events:
      - http:
          path: employees/{id}
          method: put
          cors: true  

  deleteEmployee:
    handler: src/handlers/employeeHandler.deleteEmployee
    events:
      - http:
          path: employees/{id}
          method: delete
          cors: true  

  generateToken:
    handler: src/handlers/authHandler.generateToken
    events:
      - http:
          path: auth/token
          method: post
          cors: true 
  logout:
    handler: src/handlers/authHandler.logout
    events:
      - http:
          path: auth/logout
          method: post
          cors: true 

plugins:
  - serverless-dotenv-plugin 
  - serverless-offline  

custom:
  dotenv:
    path: .env 
